/* VisTest - self-hosted visual regression testing.
 * Copyright (C) 2026 Kirill Kulagin
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of VisTest. See LICENSE for the full terms and NOTICE for
 * the trademark and commercial-licensing terms. Removing this header does not
 * remove those obligations.
 */

/**
 * The capture-hazard stand, photographed by Playwright's own toHaveScreenshot().
 *
 * Generated by nothing: every number comes from the jobs file the harness
 * (tests/capture_hazards/measure.py) writes — page addresses, the previous
 * step, masks, the launch. One test per picture, each in its own context
 * (Playwright's `page` fixture). `@baseline` tests take the baseline after
 * window.__ready and 500 ms more, under --update-snapshots=all; `@shot`
 * tests photograph the page the way a test does — goto, the step, and the
 * assertion at once — with toHaveScreenshot()'s defaults. Each result is one
 * line appended to the results file; a test whose line is there is skipped,
 * so a run that was cut off goes on where it stopped.
 */

import { appendFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { test, expect } from '@playwright/test';

const JOBS = JSON.parse(readFileSync(process.env.HAZARD_JOBS, 'utf8'));
const RESULTS = process.env.HAZARD_RESULTS;
const recorded = new Set();
if (existsSync(RESULTS)) {
  for (const line of readFileSync(RESULTS, 'utf8').split('\n')) {
    if (!line.trim()) continue;
    const r = JSON.parse(line);
    recorded.add(`${r.hazard} ${r.seed} ${r.kind} ${r.i}`);
  }
}

async function step(page, job) {
  if (job.step.kind === 'hover') await page.hover(job.step.selector);
  else if (job.step.kind === 'focus') await page.click(job.step.selector);
  else if (job.step.kind === 'scroll') await page.evaluate((y) => window.scrollTo(0, y), job.step.y);
}

const target = (page, job) => (job.target ? page.locator(job.target) : page);
const masks = (page, job) => job.mask.map((s) => page.locator(s));
/* Playwright turns '_' into '-' in a snapshot's name; the one-frame fallback
   below writes the file itself, so the name is given as Playwright keeps it. */
const snapshot = (job) => `${job.key.replace(/_/g, '-')}-${job.seed}.png`;

for (const job of JOBS) {
  test(`${job.key} ${job.seed} baseline @baseline`, async ({ page }, info) => {
    test.skip(info.project.name !== job.launch, 'another launch');
    test.skip(existsSync(join(info.project.testDir, 'snaps', snapshot(job))), 'taken');
    await page.goto(job.url);
    await page.waitForFunction(() => window.__ready === true, null, { timeout: job.ready_timeout_ms });
    await page.waitForTimeout(job.after_ready_ms);
    try {
      await expect(target(page, job)).toHaveScreenshot(snapshot(job), { mask: masks(page, job) });
    } catch (e) {
      /* A page that never holds still (the counter, the endless animation)
         gives toHaveScreenshot() no two equal frames to write: the baseline
         is then one frame, taken with the options it uses. Said in the
         results, not hidden. */
      const path = join(info.project.testDir, 'snaps', snapshot(job));
      await target(page, job).screenshot({ path, animations: 'disabled', caret: 'hide',
                                           scale: 'css', mask: masks(page, job) });
      appendFileSync(RESULTS, JSON.stringify({ tool: 'playwright', hazard: job.key, seed: job.seed,
        kind: 'baseline', i: 0, failed: false, ms: 0,
        error: 'no stable baseline from toHaveScreenshot(): one frame with its options' }) + '\n');
    }
  });

  const kinds = [['normal', job.shots, job.url], ['signal', job.signal_shots, job.signal_url]];
  for (const [kind, count, url] of kinds) {
    for (let i = 0; i < count; i++) {
      test(`${job.key} ${job.seed} ${kind} ${i} @shot`, async ({ page }, info) => {
        test.skip(info.project.name !== job.launch, 'another launch');
        test.skip(recorded.has(`${job.key} ${job.seed} ${kind} ${i}`), 'recorded');
        await page.goto(url);
        await step(page, job);
        const started = Date.now();
        let failed = false;
        let error = '';
        try {
          await expect(target(page, job)).toHaveScreenshot(snapshot(job), { mask: masks(page, job) });
        } catch (e) {
          failed = true;
          error = String(e.message || e).split('\n').map((l) => l.trim()).filter(Boolean)
            .join(' | ');
        }
        appendFileSync(RESULTS, JSON.stringify({
          tool: 'playwright', hazard: job.key, seed: job.seed, kind, i, failed,
          ms: Date.now() - started, error: error.replace(/\u001b\[[0-9;]*m/g, '').slice(0, 600),
        }) + '\n');
      });
    }
  }
}
