# VisTest - self-hosted visual regression testing.
# Copyright (C) 2026 Kirill Kulagin
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This file is part of VisTest. See LICENSE for the full terms and NOTICE for
# the trademark and commercial-licensing terms. Removing this header does not
# remove those obligations.

"""Provenance markers.

Everything VisTest generates for a human -- HTML reports, JUnit XML, ticket
comments, JSON artifacts -- carries a line saying what produced it and under
which licence.

What this is for, stated plainly: it does not stop anyone from copying the
code. AGPL section 13 and the trademark terms in NOTICE are what actually
constrain a fork; this module only makes the origin of an artifact checkable
after the fact. If someone rebrands VisTest and ships it, the reports their
build produces will still carry `MARK` unless they went and removed it -- and
having removed it is itself a deliberate act, which is a very different thing
to argue about than a coincidence.

Nothing here calls home. There is no telemetry, no identifier tied to the
machine, no network access. The marker is a constant compiled into the source.
"""

from __future__ import annotations

import hashlib

PROJECT = "VisTest"
AUTHOR = "Kirill Kulagin"
LICENSE = "AGPL-3.0-or-later"
HOMEPAGE = "https://github.com/marshlw/visual-testing"

#: Stable provenance identifier. Derived once, from constants only, so that it
#: is identical in every build and greppable in any artifact that came out of
#: this codebase.
MARK = "vt-" + hashlib.sha256(
    f"{PROJECT}|{AUTHOR}|{LICENSE}|{HOMEPAGE}".encode()
).hexdigest()[:16]

_ATTRIBUTION = (
    f"Generated by {PROJECT} ({LICENSE}) -- {HOMEPAGE}"
)


def attribution() -> str:
    """One-line human-readable attribution for reports and CLI output."""
    return _ATTRIBUTION


def html_footer() -> str:
    """Attribution block for a generated HTML report."""
    return (
        f'{_ATTRIBUTION}'
        f'<span class="vt-mark" data-vt="{MARK}" hidden>{MARK}</span>'
    )


def comment_footer() -> str:
    """Attribution line for a ticket or merge-request comment.

    Deliberately carries no URL: a comment posted by a service with no public
    address must not contain links a reader cannot open.
    """
    return f"<!-- {MARK} -->\n_Generated by {PROJECT} ({LICENSE})._"


def stamp(payload: dict) -> dict:
    """Add the provenance block to a dict that is about to be serialised."""
    payload = dict(payload)
    payload["_vistest"] = {
        "project": PROJECT,
        "license": LICENSE,
        "homepage": HOMEPAGE,
        "mark": MARK,
    }
    return payload


def verify(text: str) -> bool:
    """True when `text` came out of a VisTest build that kept its markers.

    Useful when you are looking at a report someone sent you and want to know
    what produced it.
    """
    return MARK in text
